<?php

namespace App\Models\Sushi;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Language extends Model
{
    use Sushi;

    protected $rows = [
        ['name' => 'AKAN [TWS]'],
        ['name' => 'AMHARIC [AMH]'],
        ['name' => 'ARABIC, ALGERIAN SPOKEN [ARQ]'],
        ['name' => 'ARABIC, EGYPTIAN SPOKEN [ARZ]'],
        ['name' => 'ARABIC, MESOPOTAMIAN SPOKEN [ACM]'],
        ['name' => 'ARABIC, MOROCCAN SPOKEN [ARY]'],
        ['name' => 'ARABIC, NAJDI SPOKEN [ARS]'],
        ['name' => 'ARABIC, NORTH LEVANTINE SPOKEN [APC]'],
        ['name' => 'ARABIC, SAIDI SPOKEN [AEC]'],
        ['name' => 'ARABIC, SANAANI SPOKEN [AYN]'],
        ['name' => 'ARABIC, SUDANESE SPOKEN [APD]'],
        ['name' => 'ARABIC, TUNISIAN SPOKEN [AEB]'],
        ['name' => 'ASSAMESE [ASM]'],
        ['name' => 'AWADHI [AWD]'],
        ['name' => 'AZERBAIJANI, NORTH [AZE]'],
        ['name' => 'AZERBAIJANI, SOUTH [AZB]'],
        ['name' => 'BELARUSAN [RUW]'],
        ['name' => 'BENGALI [BNG]'],
        ['name' => 'BHOJPURI [BHJ]'],
        ['name' => 'BULGARIAN [BLG]'],
        ['name' => 'BURMESE [BMS]'],
        ['name' => 'CEBUANO [CEB]'],
        ['name' => 'CHHATTISGARHI [HNE]'],
        ['name' => 'CHINESE, GAN [KNN]'],
        ['name' => 'CHINESE, HAKKA [HAK]'],
        ['name' => 'CHINESE, JINYU [CJY]'],
        ['name' => 'CHINESE, MANDARIN [CHN]'],
        ['name' => 'CHINESE, MIN BEI [MNP]'],
        ['name' => 'CHINESE, MIN NAN [CFR]'],
        ['name' => 'CHINESE, WU [WUU]'],
        ['name' => 'CHINESE, XIANG [HSN]'],
        ['name' => 'CHINESE, YUE [YUH]'],
        ['name' => 'CHITTAGONIAN [CIT]'],
        ['name' => 'CZECH [CZC]'],
        ['name' => 'DECCAN [DCC]'],
        ['name' => 'DUTCH [DUT]'],
        ['name' => 'ENGLISH [ENG]'],
        ['name' => 'FARSI, EASTERN [PRS]'],
        ['name' => 'FARSI, WESTERN [PES]'],
        ['name' => 'FRENCH [FRN]'],
        ['name' => 'FULFULDE, NIGERIAN [FUV]'],
        ['name' => 'GERMAN, STANDARD [GER]'],
        ['name' => 'GREEK [GRK]'],
        ['name' => 'GUJARATI [GJR]'],
        ['name' => 'HAITIAN CREOLE FRENCH [HAT]'],
        ['name' => 'HARYANVI [BGC]'],
        ['name' => 'HAUSA [HUA]'],
        ['name' => 'HILIGAYNON [HIL]'],
        ['name' => 'HINDI [HND]'],
        ['name' => 'HUNGARIAN [HNG]'],
        ['name' => 'IGBO [IGR]'],
        ['name' => 'ILOCANO [ILO]'],
        ['name' => 'INDONESIAN [INZ]'],
        ['name' => 'ITALIAN [ITN]'],
        ['name' => 'JAPANESE [JPN]'],
        ['name' => 'JAVANESE [JAN]'],
        ['name' => 'KANNADA [KJV]'],
        ['name' => 'KAZAKH [KAZ]'],
        ['name' => 'KHMER, CENTRAL [KMR]'],
        ['name' => 'KOREAN [KKN]'],
        ['name' => 'KURMANJI [KUR]'],
        ['name' => 'LOMBARD [LMO]'],
        ['name' => 'MADURA [MHJ]'],
        ['name' => 'MAGAHI [MQM]'],
        ['name' => 'MAITHILI [MKP]'],
        ['name' => 'MALAGASY [MEX]'],
        ['name' => 'MALAY [MLI]'],
        ['name' => 'MALAYALAM [MJS]'],
        ['name' => 'MARATHI [MRT]'],
        ['name' => 'MARWARI [MKD]'],
        ['name' => 'NAPOLETANO-CALABRESE [NPL]'],
        ['name' => 'NEPALI [NEP]'],
        ['name' => 'ORIYA [ORY]'],
        ['name' => 'OROMO, WEST-CENTRAL [GAZ]'],
        ['name' => 'PANJABI, EASTERN [PNJ]'],
        ['name' => 'PANJABI, WESTERN [PNB]'],
        ['name' => 'PASHTO, NORTHERN [PBU]'],
        ['name' => 'PASHTO, SOUTHERN [PBT]'],
        ['name' => 'POLISH [PQL]'],
        ['name' => 'PORTUGUESE [POR]'],
        ['name' => 'ROMANIAN [RUM]'],
        ['name' => 'RUSSIAN [RUS]'],
        ['name' => 'RWANDA [RUA]'],
        ['name' => 'SARAIKI [SKR]'],
        ['name' => 'SERBO-CROATIAN [SRC]'],
        ['name' => 'SHONA [SHD]'],
        ['name' => 'SINDHI [SND]'],
        ['name' => 'SINHALA [SNH]'],
        ['name' => 'SOMALI [SOM]'],
        ['name' => 'SPANISH [SPN]'],
        ['name' => 'SUNDA [SUO]'],
        ['name' => 'SWEDISH [SWD]'],
        ['name' => 'TAGALOG [TGL]'],
        ['name' => 'TAMIL [TCV]'],
        ['name' => 'TATAR [TTR]'],
        ['name' => 'TELUGU [TCW]'],
        ['name' => 'THAI [THJ]'],
        ['name' => 'THAI, NORTHEASTERN [TTS]'],
        ['name' => 'TURKISH [TRK]'],
        ['name' => 'UKRAINIAN [UKR]'],
        ['name' => 'URDU [URD]'],
        ['name' => 'UYGHUR [UIG]'],
        ['name' => 'UZBEK, NORTHERN [UZB]'],
        ['name' => 'VIETNAMESE [VIE]'],
        ['name' => 'YORUBA [YOR]'],
        ['name' => 'ZHUANG, NORTHERN [CCX]'],
        ['name' => 'ZULU [ZUU]']
    ];
}